version: '3.8'

services:
  terraria:
    image: ryshe/terraria:vanilla-latest
    container_name: octopus_terraria
    restart: always
    ports:
      - "7777:7777"
    volumes:
      - terraria_world:/root/.local/share/Terraria/Worlds
    command: >
      bash -c "
      if [ -f /root/.local/share/Terraria/Worlds/Octopus.wld ]; then
        ./TerrariaServer.bin.x86_64 -world /root/.local/share/Terraria/Worlds/Octopus.wld -autocreate 0
      else
        ./TerrariaServer.bin.x86_64 -world /root/.local/share/Terraria/Worlds/Octopus.wld -autocreate 2 -worldname 'Octopus World' -difficulty 0 -maxplayers 16 -port 7777 -seed 05162020
      fi
      "

volumes:
  terraria_world:
