version: '3.8'

services:
  terraria:
    image: ryshe/terraria:vanilla-latest
    container_name: octopus_terraria
    restart: always
    # These two lines are crucial for Terraria to accept input/output correctly
    tty: true
    stdin_open: true
    ports:
      - "7777:7777"
    environment:
      - WORLD_FILENAME=Octopus.wld
      - WORLD_NAME=Octopus World
      - SEED=05162020
      - DIFFICULTY=0
      - MAX_PLAYERS=16
    volumes:
      - terraria_world:/root/.local/share/Terraria/Worlds

volumes:
  terraria_world: