version: '3.8'

services:
  terraria:
    image: beardedio/terraria:latest
    container_name: octopus_terraria
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "7777:7777"
    volumes:
      - terraria_world:/world
      - ./serverconfig.txt:/config/serverconfig.txt:ro
    environment:
      - WORLD=/world/Octopus.wld
      - AUTOCREATE=2
      - WORLDNAME=Octopus World
      - MAXPLAYERS=16
      - PORT=7777
      - PASSWORD=
      - DIFFICULTY=1
      - MOTD=Welcome to Octopus Technology!

volumes:
  terraria_world:
