version: '3.8'

services:
  terraria:
    image: ryshe/terraria:vanilla-latest
    container_name: octopus_terraria
    restart: always
    tty: true
    stdin_open: true
    ports:
      - "7777:7777"
    environment:
      - WORLD_FILENAME=Octopus.wld
      - WORLD_NAME=Octopus World
      - SEED=05162020
      - DIFFICULTY=0
      - MAX_PLAYERS=16
      # 1=Small, 2=Medium, 3=Large. This triggers the creation if the file is missing.
      - AUTOCREATE=2 
    volumes:
      - terraria_world:/root/.local/share/Terraria/Worlds

volumes:
  terraria_world: