version: '3.8'

services:
  terraria:
    image: ryshe/terraria:vanilla-latest
    container_name: octopus_terraria
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "7777:7777"
    volumes:
      - terraria_world:/root/.local/share/Terraria/Worlds

volumes:
  terraria_world:
